config/routes.rb
BlueprintBazaar::Application.routes.draw do
  resources :projects

  get "user_sessions/new"

  get "user_sessions/create"

  get "user_sessions/destroy"

  root :to => 'home#index'
  resources :user_sessions
  resources :users

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/project.rb
class Project
    include Mongoid::Document
    include Mongoid::Timestamps


    field :title, type: String
    field :description, type: String
    field :upvotes, type: Integer, default: 0
    field :downvotes, type: Integer, default: 0
    field :torrent_url, type: String
    field :image_urls, type: Array
    field :featured_at, type: Time
    field :creator, type: String

    # referenced relations
    #has_one :creator, :inverse_of => :user
    has_and_belongs_to_many :tags, inverse_of: nil
    belongs_to :user, inverse_of: :projects

    # embedded relations
    embeds_many :steps
    embeds_many :comments

    validates_presence_of :title
    validates_presence_of :description

    attr_accessible :title, :description, :torrent_url, :image_urls, :steps, :updated_at, :featured_at
end

class Comment
    include Mongoid::Document
    field :body
    has_one :commentor, class_name: User
    embedded_in :project, inverse_of: :comments
end

class Step
    include Mongoid::Document
    field :title
    field :image_urls
    field :body
    field :video_url

    embedded_in :project, inverse_of: :steps
end

class Tag
    include Mongoid::Document
    field :name, type: String
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_filter :require_login, :only => [:index, :show]
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.creator = params[:project][:creator]
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    if @project.owner._id == @current_user._id
        @project.destroy
        respond_to do |format|
            format.html { redirect_to projects_url }
            format.json { head :no_content }
        end
    else
        respond_to do |format|
            format.html { redirect_to projects_url, alert: "You are not authorized to delete #{@project.title}" }
            format.json { render json: @project.errors, status: :unauthorized }
            #TODO: Create admin notification for unauthorized deletion attempt
        end
    end

  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.slim
.row.content
  .quarter
    h3 Creating a New Project
    |
      We're really glad that you want to share your great ideas with the rest of the world. Tell us a little bit about your project so that we can help others find it as easily as possible
    br
    br
    h5 Guidelines
    small
      |
        Blueprint Bazaar is intended for sharing free and open source (FOSS) designs for physical objects that can be produced using automated fabrication tools, such as 3D printers, CNC routers and mills, and other computer-controlled manufacturing devices. We want to allow as many kinds of objects as possible, but unfortunately we have to disallow some types of projects. These include:
    small
      ul
        li
          small Projects with non-FOSS licenses
        li
          small Projects that infringe on the copyrights of others
          ul
            li
              small designs covered under fair use exceptions, such as parodies, are allowed
        li
          small Functional weapons or designs that are intended to be converted to functional weapons.
          ul
            li
              small Non-functional props, toys, airsoft/paintball, and the like are acceptable.
        li
          small Drug paraphenalia


  .threequarter
    = form_for @project, :html => { :class => 'forms' } do |f|
      .row
        = f.hidden_field :creator, value: current_user._id
        #step1
          h3 Step 1: Tell us about the project!
          .row
            .half
              b What is the project called?
              br
              = f.text_field :title
            .half
              b Where is the project's torrent file located?
              br
              = f.text_field :torrent_url
          .row

            .half
              b What kind of project is it?
              br
          .row
            b Give us a brief description of it:
            br
            = f.text_area :description, :cols => 40, :rows => 3;


        #step2
          h3 Step 2: Add some pictures!
        #step3
          h3 Step 3: Read our awesome legal docs!
      .row
        = link_to 'Cancel', projects_path, :class => 'btn', style: "float:left;"
        = f.submit nil, class: 'btn', id: "submitProject", style: "float:right;display:none;"
        a.btn#next href="#" onClick="nextStep()" style="float:right" Next
        a.btn#prev href="#" onClick="previousStep()" style="float:right" Previous

app/views/projects/_preview.html.slim
.project-preview
  .row.photo
    a href="#{project_path(preview)}"
      - if preview.image_urls
        img src="#{preview.image_urls[0]}"
      - else
        img src="http://placehold.it/150x150&text=Preview+Unavailable"
  .row.project-details
    .big
      a href="#{project_path preview}" class="title"
        = preview.title
    .small
      | Created by&nbsp;
      a href="#{user_path preview.creator}" = preview.creator

app/views/projects/edit.html.slim
= content_for :content do
  h1= "Edit #{Project.model_name.human}"
  = render :partial => "form"

app/views/projects/index.html.slim
= content_for :content do
  h1 Projects
  table.striped
    thead.thead-black
      tr
        /th= model_class.human_attribute_name(:id)
        th Title
        /th= model_class.human_attribute_name(:description)
        /th= model_class.human_attribute_name(:instructions)
        th Creator
        /
        /th= model_class.human_attribute_name(:repo_url)
        /th= model_class.human_attribute_name(:image_url)
        th Upvotes
        th Downvotes
        /th= model_class.human_attribute_name(:featured_on)
        th Created On
        th Actions
    tbody
      - @projects.each do |project|
        tr
          td= link_to project.title, project_path(project)
          td= project.creator
          /td= project.description
          /td= project.instructions
          /td= project.author
          /td= project.repo_url
          /td= project.image_url
          td= project.upvotes
          td= project.downvotes
          /td= project.featured_on
          td= project.created_at
          td
            = link_to 'Edit', edit_project_path(project), :class => 'btn btn-small'
            = link_to 'Destroy', project_path(project), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-small'

  = link_to 'New', new_project_path, :class => 'btn'

app/views/projects/new.html.slim
/= content_for :javascript do

= content_for :content do
  = render :partial => "form"

app/views/projects/show.html.slim
- model_class = Project

= content_for :content_menu do
  ul
    li
      a href="#" Overview
    li
      a href="#" Instructions
    li
      a href="#" asdf
    li
      a href="#" asdf


= content_for :content_header do
  .twothird
    .project-created-by
      .project-info
        .voting-mechanism
          .arrow.up
            = icon_tag "arrow-up"
          .score
            #upvotes
              = @project.upvotes
          .score
            #difference
              = @project.upvotes - @project.downvotes
          .score
            #downvotes
              = @project.downvotes
          .arrow.down
            = icon_tag "arrow-down"
        .avatar
          a href="#"
            img src="http://placehold.it/64x64"/
        .project-info-text
          h3 #{@project.title}
          .project-creator
            | Created by #{@project.creator}
          .project-featured-on
            - if @project.featured_at
              | Featured on: #{@project.featured_at}

  .push-right.third
    .inner.row
      .project-buttons
        span.btn-group
          button.btn.btn-large Download
          button.btn.btn-large Visit Repository


= content_for :content do
  .row.content
    .content-body
      .row
        .half
          .row
            img src="http://placehold.it/1280x800"
          .row
            .quarter
              img src="http://placehold.it/1280x800"
            .quarter
              img src="http://placehold.it/1280x800"
            .quarter
              img src="http://placehold.it/1280x800"
            .quarter
              img src="http://placehold.it/1280x800"
        .half
          .row
            h3 Introduction
            = @project.description
      /.row
        .half
        .half
          b
            = model_class.human_attribute_name(:instructions) + ':'
          br
          = @project.instructions