config/routes.rb
BlueprintBazaar::Application.routes.draw do
  resources :projects

  get "user_sessions/new"

  get "user_sessions/create"

  get "user_sessions/destroy"

  root :to => 'home#index'
  resources :user_sessions
  resources :users

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout

end

app/controllers/user_sessions_controller.rb
# app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
    skip_before_filter :require_login, :except => [:destroy]
    def new
        @user = User.new
    end

    def create
        respond_to do |format|
            if @user = login(params[:_id],params[:password])
                format.html { redirect_back_or_to(:users, :notice => 'Login successful.') }
                format.xml { render :xml => @user, :status => :created, :location => @user }
            else
                format.html { flash.now[:alert] = "Login failed."; render :action => "new" }
                format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
            end
        end
    end

    def destroy
        logout
        redirect_to(:users, :notice => 'Logged out!')
    end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.slim
= form_tag user_sessions_path, :method => :post do
  .field
    = label_tag :_id
    br
    = text_field_tag :_id

  .field
    = label_tag :password
    br
    = password_field_tag :password

  .actions
    = submit_tag "Login"

app/views/user_sessions/create.html.slim
h1 UserSessions#create
p Find me in app/views/user_sessions/create.html.slim

app/views/user_sessions/destroy.html.slim
h1 UserSessions#destroy
p Find me in app/views/user_sessions/destroy.html.slim

app/views/user_sessions/new.html.slim
= content_for :content do
  h1 Login

  = render 'form'

  = link_to 'Back', user_sessions_path